---
title: "read_results"
author: "Yihan Bao yb254"
date: "2/25/2024"
output: html_document
---

```{r}
# marginal, delta = 3, nsim = 200
`result_simulation_improved(marginal)` <- readRDS("~/Desktop/research/uci research/github code for modified EMEE/result_simulation_improved(marginal).RDS")
colnames(`result_simulation_improved(marginal)`) <-  c("Estimator", "Sample Size",rep(c("Bias","SD","RMSE","CP(unadj)"),1))
`result_simulation_improved(marginal)`[3:6] <- round(`result_simulation_improved(marginal)`[3:6], 3)
`result_simulation_improved(marginal)`
```
```{r}
result_simulation_improved <- readRDS("~/Desktop/research/uci research/github code for modified EMEE/result_simulation_improved.RDS")
result_simulation_improved <- result_simulation_improved[,c(1,2,3,5,7,9,4,6,8,10)]
colnames(result_simulation_improved) <-  c("Estimator", "Sample Size",rep(c("Bias","SD","RMSE","CP(unadj)"),2))
result_simulation_improved[,3:10] <- round(result_simulation_improved[,3:10], 3)
result_simulation_improved
```
```{r}
`result_simulation_improved(marginal, Delta = 10)` <- readRDS("~/Desktop/research/uci research/github code for modified EMEE/result_simulation_improved(marginal, Delta = 10).RDS")
`result_simulation_improved(marginal, Delta = 10)`[3:6] <- round(`result_simulation_improved(marginal, Delta = 10)`[3:6], 3)
`result_simulation_improved(marginal, Delta = 10)`
```

